version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::412381740883:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-3bktWcJa5XsU"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::412381740883:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-4HtPAn8iTbLj"
cloudformation_execution_role = "arn:aws:iam::412381740883:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-ut19JNGw4f3X"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-l7db7twg51bz"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::412381740883:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-3r5xdUrCrVRb"
cloudformation_execution_role = "arn:aws:iam::412381740883:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-AfbHdxQe7EKU"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-pmrskvtu1iqi"
image_repository = ""
region = "us-east-1"
